;;; chiaroscuro-theme.el --- Theme consisting of multiple themes  -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme/common/default.el")

;;; load light or dark diff colors
(if (>= INDEX-CHIAROSCURO INDEX-HIGH-CONTRAST)
    (load-file "~/.emacs.d/theme/common/diff-dark.el")
  (load-file "~/.emacs.d/theme/common/diff-light.el"))

;;; dark themes start here
(if (>= INDEX-CHIAROSCURO INDEX-LOW-CHROMA)
    (load-file "~/.emacs.d/theme/common/dark.el")
  (load-file "~/.emacs.d/theme/common/light.el"))

(setq theme-map
      `((,INDEX-ECLIPSE . "~/.emacs.d/theme/light/eclipse.el")
        (,INDEX-COLOR-CHANGE-LIGHT . "~/.emacs.d/theme/color-changer/color-changer.el")
        (,INDEX-HIGH-CONTRAST . "~/.emacs.d/theme/light/high-contrast.el")
        (,INDEX-GRAY . "~/.emacs.d/theme/light/gray.el")
        (,INDEX-LOW-CHROMA . "~/.emacs.d/theme/dark/low-chroma.el")
        (,INDEX-BLUE . "~/.emacs.d/theme/dark/blue.el")
        (,INDEX-NEON . "~/.emacs.d/theme/dark/neon.el")
        (,INDEX-RED . "~/.emacs.d/theme/dark/red.el")
        (,INDEX-CASABLANCA . "~/.emacs.d/theme/dark/casablanca.el")
        (,INDEX-COLOR-CHANGE-DARK . "~/.emacs.d/theme/color-changer/color-changer.el")))

(let ((theme-file (assoc-default INDEX-CHIAROSCURO theme-map)))
  (when (and theme-file (> INDEX-CHIAROSCURO INDEX-DEFAULT))
    (load-file theme-file)))

(deftheme chiaroscuro)

(custom-theme-set-faces 'chiaroscuro

`(ac-candidate-face ((t (:foreground ,text-normal :background ,background-fringe ))))
`(ac-candidate-mouse-face ((t (:foreground ,text-normal :background ,background-fringe ))))
`(ac-completion-face ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(ac-selection-face ((t (:foreground ,text-normal :background ,background-fringe :bold t ))))
`(ansi-color-bold ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(auto-dim-other-buffers ((t (:foreground ,text-low :background unspecified ))))
`(avy-lead-face ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(avy-lead-face-0 ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(avy-lead-face-1 ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(avy-lead-face-2 ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(bookmark-face ((t (:foreground ,text-normal :background unspecified ))))
`(comint-highlight-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(company-preview ((t (:foreground ,text-normal :background ,background-tooltip :bold t ))))
`(company-preview-common ((t (:foreground ,text-normal :background ,background-tooltip :bold t ))))
`(company-preview-search ((t (:foreground ,text-normal :background ,background-tooltip :bold t ))))
`(company-tooltip ((t (:foreground ,text-normal :background ,background-tooltip ))))
`(company-tooltip-annotation ((t (:foreground ,text-lower :background ,background-tooltip ))))
`(company-tooltip-annotation-selection ((t (:foreground ,text-match-2-low :background ,background-match-2 ))))
`(company-tooltip-common ((t (:foreground ,text-normal :background ,background-tooltip :bold t ))))
`(company-tooltip-common-selection ((t (:foreground ,text-match-2 :background ,background-match-2 :bold t ))))
`(company-tooltip-selection ((t (:foreground ,text-match-2 :background ,background-match-2 ))))
`(compilation-info ((t (:foreground ,text-link :bold t :underline t ))))
`(cua-rectangle ((t (:foreground ,text-region :background ,background-region :bold t ))))
`(cursor ((t (:background ,background-cursor ))))
`(custom-button ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(dap-ui-breakpoint-verified-fringe ((t (:foreground ,text-normal :background unspecified ))))
`(dap-ui-marker-face ((t (:foreground ,text-hl :background ,background-hl ))))
`(default ((t (:foreground ,text-normal :background ,background ))))
`(diff-file-header ((t (:foreground ,text-normal :background ,background-magit :bold t ))))
`(diff-header ((t (:foreground ,text-normal :background ,background-magit ))))
`(dired-directory ((t (:foreground ,text-low :background unspecified :bold t ))))
`(dired-flagged ((t (:foreground ,text-normal :background unspecified ))))
`(dired-header ((t (:foreground ,text-low :background unspecified :bold t ))))
`(dired-ignored ((t (:foreground ,text-normal :background unspecified ))))
`(dired-mark ((t (:foreground ,text-normal :background unspecified ))))
`(dired-marked ((t (:foreground ,text-normal :background unspecified ))))
`(dired-narrow-blink ((t (:foreground ,text-normal :background unspecified ))))
`(dired-perm-write ((t (:foreground ,text-normal :background unspecified ))))
`(dired-set-id ((t (:foreground ,text-normal :background unspecified ))))
`(dired-special ((t (:foreground ,text-normal ))))
`(dired-symlink ((t (:foreground ,text-normal :background unspecified ))))
`(dired-warning ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-compressed-file-name ((t (:foreground ,text-low :background unspecified ))))
`(diredfl-compressed-file-suffix ((t (:foreground ,text-low :background unspecified :bold t :italic t ))))
`(diredfl-date-time ((t (:foreground ,text-low :background unspecified ))))
`(diredfl-deletion ((t (:foreground ,text-delete :background unspecified :bold t ))))
`(diredfl-deletion-file-name ((t (:foreground ,text-delete :background unspecified :bold t :strike-through t ))))
`(diredfl-dir-heading ((t (:foreground ,text-link :background unspecified :bold t ))))
`(diredfl-dir-name ((t (:foreground ,text-directory :background ,background-directory :bold t ))))
`(diredfl-dir-priv ((t (:foreground ,text-directory :background ,background-directory ))))
`(diredfl-exec-priv ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-file-name ((t (:foreground ,text-normal :background unspecified ))))
`(diredfl-file-suffix ((t (:foreground ,text-low :background unspecified ))))
`(diredfl-flag-mark ((t (:foreground ,text-match-2 :background unspecified :bold t ))))
`(diredfl-flag-mark-line ((t (:foreground ,text-match-2 :background ,background-match-2 ))))
`(diredfl-ignored-file-name ((t (:foreground ,text-normal :background unspecified :bold t :italic t ))))
`(diredfl-link-priv ((t (:foreground ,text-link :background unspecified :bold t :underline t ))))
`(diredfl-no-priv ((t (:foreground ,text-lower :background unspecified ))))
`(diredfl-number ((t (:foreground ,text-low :background unspecified ))))
`(diredfl-other-priv ((t (:foreground ,text-low :background unspecified :bold t ))))
`(diredfl-rare-priv ((t (:foreground ,text-diff-added-highlight :background ,background-diff-added-highlight ))))
`(diredfl-read-priv ((t (:foreground ,text-lower :background unspecified ))))
`(diredfl-symlink ((t (:foreground ,text-link :background unspecified :bold t :underline t ))))
`(diredfl-write-priv ((t (:foreground ,text-low :background unspecified ))))
`(ediff-current-diff-A ((t (:foreground "#000000" :background ,background-diff-current-A ))))
`(ediff-current-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-current-Ancestor ))))
`(ediff-current-diff-B ((t (:foreground "#000000" :background ,background-diff-current-B ))))
`(ediff-current-diff-C ((t (:foreground "#000000" :background ,background-diff-current-C ))))
`(ediff-even-diff-A ((t (:foreground "#000000" :background ,background-diff-even-A ))))
`(ediff-even-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-even-Ancestor ))))
`(ediff-even-diff-B ((t (:foreground "#000000" :background ,background-diff-even-B ))))
`(ediff-even-diff-C ((t (:foreground "#000000" :background ,background-diff-even-C ))))
`(ediff-fine-diff-A ((t (:foreground "#000000" :background ,background-diff-fine-A ))))
`(ediff-fine-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-fine-Ancestor ))))
`(ediff-fine-diff-B ((t (:foreground "#000000" :background ,background-diff-fine-B ))))
`(ediff-fine-diff-C ((t (:foreground "#000000" :background ,background-diff-fine-C ))))
`(ediff-odd-diff-A ((t (:foreground "#000000" :background ,background-diff-odd-A ))))
`(ediff-odd-diff-Ancestor ((t (:foreground "#000000" :background ,background-diff-odd-Ancestor ))))
`(ediff-odd-diff-B ((t (:foreground "#000000" :background ,background-diff-odd-B ))))
`(ediff-odd-diff-C ((t (:foreground "#000000" :background ,background-diff-odd-C ))))
`(eglot-diagnostic-tag-unnecessary-face ((t (:foreground ,text-warning :background unspecified :bold t ))))
`(eglot-mode-line ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(elfeed-log-date-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-debug-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-error-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-info-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-log-warn-level-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-date-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-feed-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-filter-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-last-update-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-tag-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-title-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-unread-count-face ((t (:foreground ,text-normal :background unspecified ))))
`(elfeed-search-unread-title-face ((t (:foreground ,text-normal :background unspecified ))))
`(escape-glyph ((t (:foreground ,text-whitespace :background unspecified ))))
`(eshell-ls-directory ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(eshell-prompt ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-search ((t (:foreground ,text-normal :background unspecified ))))
`(evil-ex-substitute-matches ((t (:foreground ,text-normal :background unspecified ))))
`(eww-form-checkbox ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-select ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-submit ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-text ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-form-textarea ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(eww-valid-certificate ((t (:foreground ,text-normal :background ,background-mode-line :bold t ))))
`(flycheck-error ((t (:foreground ,text-error :bold t :underline t ))))
`(flycheck-error-list-checker-name ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-column-number ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-error ((t (:foreground ,text-error :bold t :underline t ))))
`(flycheck-error-list-error-message ((t (:foreground ,text-error :bold t ))))
`(flycheck-error-list-filename ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-highlight ((t (:foreground ,text-normal :bold t :underline t ))))
`(flycheck-error-list-id ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-id-with-explainer ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-info ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-line-number ((t (:foreground ,text-normal :bold t ))))
`(flycheck-error-list-warning ((t (:foreground ,text-warning :bold t ))))
`(flycheck-fringe-error ((t (:foreground ,text-error :bold t ))))
`(flycheck-fringe-info ((t (:foreground ,text-info :bold t ))))
`(flycheck-fringe-warning ((t (:foreground ,text-warning :bold t ))))
`(focus-unfocused ((t (:foreground ,text-lower ))))
`(font-lock-bracket-face ((t (:foreground ,text-normal ))))
`(font-lock-builtin-face ((t (:foreground ,text-type :bold t ))))
`(font-lock-comment-delimiter-face ((t (:foreground ,text-comment ))))
`(font-lock-comment-face ((t (:foreground ,text-comment ))))
`(font-lock-constant-face ((t (:foreground ,text-constant ))))
`(font-lock-doc-face ((t (:foreground ,text-comment ))))
`(font-lock-function-call-face ((t (:foreground ,text-normal ))))
`(font-lock-function-name-face ((t (:foreground ,text-function :bold t ))))
`(font-lock-keyword-face ((t (:foreground ,text-keyword :bold t ))))
`(font-lock-number-face ((t (:foreground ,text-normal ))))
`(font-lock-preprocessor-face ((t (:foreground ,text-preprocessor ))))
`(font-lock-regexp-face ((t (:foreground ,text-normal :bold t ))))
`(font-lock-regexp-grouping-backslash ((t (:foreground ,text-normal ))))
`(font-lock-regexp-grouping-construct ((t (:foreground ,text-low ))))
`(font-lock-string-face ((t (:foreground ,text-comment ))))
`(font-lock-type-face ((t (:foreground ,text-type :bold t ))))
`(font-lock-variable-name-face ((t (:foreground ,text-variable :bold t ))))
`(font-lock-variable-use-face ((t (:foreground ,text-variable ))))
`(font-lock-warning-face ((t (:foreground ,text-mode-line ))))
`(fringe ((t (:foreground ,text-normal :background ,background-fringe ))))
`(header-line ((t (:foreground ,text-normal ))))
`(helm-M-x-key ((t (:foreground ,text-match-2 ))))
`(helm-buffer-directory ((t (:foreground ,text-directory :background ,background-directory :bold t ))))
`(helm-buffer-file ((t (:foreground ,text-normal :background unspecified ))))
`(helm-buffer-process ((t (:foreground ,text-low :background unspecified ))))
`(helm-buffer-size ((t (:foreground ,text-low :background unspecified ))))
`(helm-candidate-number ((t (:foreground ,text-normal ))))
`(helm-ff-directory ((t (:foreground ,text-normal :bold t ))))
`(helm-ff-dotted-directory ((t (:foreground ,text-low :background unspecified ))))
`(helm-ff-executable ((t (:foreground ,text-normal :background unspecified ))))
`(helm-ff-file-extension ((t (:foreground ,text-low :background unspecified :bold nil ))))
`(helm-ff-nofile ((t (:foreground ,text-normal :background unspecified ))))
`(helm-ff-prefix ((t (:foreground ,text-normal :background unspecified ))))
`(helm-ff-rsync-progress ((t (:foreground ,text-normal ))))
`(helm-grep-file ((t (:foreground ,text-normal :background unspecified :bold t :underline t ))))
`(helm-grep-finish ((t (:foreground ,text-normal :background unspecified ))))
`(helm-grep-lineno ((t (:foreground ,text-low ))))
`(helm-grep-match ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(helm-lsp-diag-error ((t (:foreground ,text-error :bold t :underline t ))))
`(helm-lsp-diag-info ((t (:foreground ,text-error :bold t :underline t ))))
`(helm-match ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-match-item ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-minibuffer-prompt ((t (:foreground ,text-match-3 :background ,background-match-3 ))))
`(helm-non-file-buffer ((t (:foreground ,text-low :background unspecified :italic t ))))
`(helm-selection ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-selection-line ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(helm-separator ((t (:foreground ,text-low :background unspecified ))))
`(helm-source-header ((t (:foreground ,text-highlight-2 :background unspecified :bold t :height 1.3 :family "Sans Serif" ))))
`(helm-swoop-target-line-block-face ((t (:foreground ,text-match-2 :background ,background-match-2 ))))
`(helm-swoop-target-line-face ((t (:foreground ,text-match-2 :background ,background-match-2 :bold t ))))
`(helm-swoop-target-word-face ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(help-key-binding ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(highlight ((t (:foreground ,text-normal :background unspecified ))))
`(hl-line ((t (:foreground ,text-hl :background ,background-hl ))))
`(hydra-face-blue ((t (:foreground ,text-highlight-1 :background unspecified :bold t ))))
`(hydra-face-red ((t (:foreground ,text-highlight-2 :background unspecified :bold t ))))
`(ido-first-match ((t (:foreground ,text-match-1 :background ,background-hl ))))
`(ido-only-match ((t (:foreground ,text-match-1 :background ,background-hl ))))
`(ido-subdir ((t (:foreground ,text-normal ))))
`(iedit-occurrence ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(info-menu-star ((t (:foreground ,text-normal :background unspecified ))))
`(info-node ((t (:foreground ,text-normal :background unspecified :bold t :italic t ))))
`(info-xref ((t (:foreground ,text-link :background unspecified :underline t ))))
`(info-xref-visited ((t (:foreground ,text-low :background unspecified :underline t ))))
`(isearch ((t (:foreground ,text-normal :background unspecified ))))
`(ivy-current-match ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(ivy-minibuffer-match-face-1 ((t (:foreground ,text-match-2-a :background ,background-match-2-a :bold t ))))
`(ivy-minibuffer-match-face-2 ((t (:foreground ,text-match-2-b :background ,background-match-2-b :bold t ))))
`(ivy-minibuffer-match-face-3 ((t (:foreground ,text-match-2-c :background ,background-match-2-c :bold t ))))
`(ivy-minibuffer-match-face-4 ((t (:foreground ,text-match-2-d :background ,background-match-2-d :bold t ))))
`(lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(lazy-highlight ((t (:foreground ,text-normal :background unspecified ))))
`(line-number ((t (:foreground ,text-hl-low :background unspecified ))))
`(line-number-current-line ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(line-number-major-tick ((t (:foreground ,text-hl-low :background unspecified ))))
`(line-number-minor-tick ((t (:foreground ,text-hl-low :background unspecified ))))
`(link ((t (:foreground ,text-normal :underline t ))))
`(lsp-face-highlight-read ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(lsp-face-highlight-write ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(lsp-flycheck-warning-unnecessary-face ((t (:foreground ,text-warning :bold t :underline t ))))
`(lsp-headerline-breadcrumb-separator-face ((t (:foreground ,text-low :background unspecified ))))
`(magit-blame-heading ((t (:foreground ,text-low :background ,background-low ))))
`(magit-blame-highlight ((t (:foreground ,text-low :background ,background-low ))))
`(magit-blame-margin ((t (:foreground ,text-lower :background ,background-fringe ))))
`(magit-branch-current ((t (:foreground ,text-highlight-1 :background unspecified :bold t :box (:line-width 1 :color ,text-highlight-1) ))))
`(magit-branch-local ((t (:foreground ,text-highlight-2 :background unspecified :bold t :box (:line-width 1 :color ,text-highlight-2) ))))
`(magit-branch-remote ((t (:foreground ,text-highlight-2 :background unspecified :bold t :box (:line-width 1 :color ,text-highlight-2) ))))
`(magit-branch-remote-head ((t (:foreground ,text-highlight-2 :background unspecified :bold t :box (:line-width 1 :color ,text-highlight-2) :bold t :italic t ))))
`(magit-branch-upstream ((t (:foreground ,text-low :background unspecified :bold t :box (:line-width 1 :color ,text-low) ))))
`(magit-diff-added ((t (:foreground "#000000" :background ,background-diff-added ))))
`(magit-diff-added-highlight ((t (:foreground "#000000" :background ,background-diff-added-highlight ))))
`(magit-diff-conflict-heading ((t (:foreground ,text-normal :background unspecified ))))
`(magit-diff-context ((t (:foreground ,text-low :background unspecified ))))
`(magit-diff-context-highlight ((t (:foreground ,text-hl-low :background ,background-hl-low ))))
`(magit-diff-file-heading ((t (:\foreground ,text-low :background unspecified :bold t ))))
`(magit-diff-file-heading-highlight ((t (:foreground ,text-hl-low :background ,background-hl-low :bold t ))))
`(magit-diff-file-heading-selection ((t (:foreground ,text-hl-low :background ,background-hl-low :bold t ))))
`(magit-diff-hunk-heading ((t (:foreground ,text-low :background ,background-low ))))
`(magit-diff-hunk-heading-highlight ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t ))))
`(magit-diff-hunk-heading-selection ((t (:foreground ,text-normal :background unspecified ))))
`(magit-diff-removed ((t (:foreground "#000000" :background ,background-diff-removed ))))
`(magit-diff-removed-highlight ((t (:foreground "#000000" :background ,background-diff-removed-highlight ))))
`(magit-hash ((t (:foreground ,text-low ))))
`(magit-header-line ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t ))))
`(magit-header-line-key ((t (:foreground ,text-normal :bold t ))))
`(magit-keyword-squash ((t (:foreground ,text-normal ))))
`(magit-log-author ((t (:foreground ,text-hl-lower ))))
`(magit-log-date ((t (:foreground ,text-hl-lower ))))
`(magit-reflog-amend ((t (:foreground ,text-normal ))))
`(magit-reflog-checkout ((t (:foreground ,text-normal ))))
`(magit-reflog-cherry-pick ((t (:foreground ,text-normal ))))
`(magit-reflog-commit ((t (:foreground ,text-normal ))))
`(magit-reflog-merge ((t (:foreground ,text-normal ))))
`(magit-reflog-other ((t (:foreground ,text-normal ))))
`(magit-reflog-rebase ((t (:foreground ,text-normal ))))
`(magit-reflog-remote ((t (:foreground ,text-normal ))))
`(magit-reflog-reset ((t (:foreground ,text-normal ))))
`(magit-section-heading ((t (:foreground ,text-low :bold t ))))
`(magit-section-highlight ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(magit-sequence-head ((t (:foreground ,text-normal :bold t ))))
`(match ((t (:foreground ,text-hl :background ,background-hl :bold t ))))
`(message-header-cc ((t (:foreground ,text-normal ))))
`(message-header-name ((t (:foreground ,text-normal ))))
`(message-header-newsgroups ((t (:foreground ,text-normal ))))
`(message-header-other ((t (:foreground ,text-normal ))))
`(message-header-subject ((t (:foreground ,text-normal ))))
`(message-header-to ((t (:foreground ,text-normal ))))
`(minibuffer-prompt ((t (:foreground ,text-match-3 :background ,background-match-3 ))))
`(mode-line ((t (:foreground ,text-mode-line :background ,background-mode-line :box (:line-width 8 :color ,background-mode-line) ))))
`(mode-line-inactive ((t (:foreground ,text-mode-line-inactive :background ,background-mode-line-inactive :box (:line-width 8 :color ,background-mode-line-inactive) ))))
`(nxml-element-local-name ((t (:foreground ,text-normal :background unspecified ))))
`(nxml-tag-delimiter ((t (:foreground ,text-low :background unspecified ))))
`(org-agenda-column-dateline ((t (:foreground ,text-normal :underline t ))))
`(org-agenda-date ((t (:foreground ,text-low :bold t ))))
`(org-agenda-date-today ((t (:foreground ,text-normal :bold t :italic t ))))
`(org-agenda-date-weekend ((t (:foreground ,text-lower :bold t ))))
`(org-agenda-diary ((t (:foreground ,text-normal ))))
`(org-agenda-dimmed-todo-face ((t (:foreground ,text-low ))))
`(org-agenda-done ((t (:foreground ,text-lower :background unspecified ))))
`(org-agenda-filter-category ((t (:foreground ,text-normal ))))
`(org-agenda-filter-effort ((t (:foreground ,text-normal ))))
`(org-agenda-filter-regexp ((t (:foreground ,text-normal ))))
`(org-agenda-filter-tags ((t (:foreground ,text-normal ))))
`(org-agenda-restriction-lock ((t (:foreground ,text-normal ))))
`(org-agenda-structure ((t (:foreground ,text-low ))))
`(org-archived ((t (:foreground ,text-normal :background unspecified ))))
`(org-block ((t (:foreground ,text-low :background ,background-low :italic t ))))
`(org-block-begin-line ((t (:foreground ,text-lower :background unspecified ))))
`(org-block-end-line ((t (:foreground ,text-lower :background unspecified ))))
`(org-checkbox-statistics-done ((t (:foreground ,text-low :background unspecified ))))
`(org-column ((t (:foreground ,text-normal :background unspecified ))))
`(org-column-title ((t (:foreground ,text-normal :background unspecified ))))
`(org-date ((t (:foreground ,text-link :underline t ))))
`(org-date-selected ((t (:foreground ,text-normal :background ,background-hl ))))
`(org-document-info ((t (:foreground ,text-normal :background unspecified ))))
`(org-document-info-keyword ((t (:foreground ,text-normal :background unspecified ))))
`(org-document-title ((t (:foreground ,text-normal :background unspecified ))))
`(org-done ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t :strike-through t ))))
`(org-drawer ((t (:foreground ,text-normal :background unspecified ))))
`(org-ellipsis ((t (:foreground ,text-normal :background unspecified ))))
`(org-footnote ((t (:foreground ,text-normal :background unspecified ))))
`(org-formula ((t (:foreground ,text-normal :background unspecified ))))
`(org-headline-done ((t (:foreground ,background-match-3 :background ,background :strike-through t ))))
`(org-headline-todo ((t (:foreground ,text-normal :background unspecified ))))
`(org-hide ((t (:foreground ,text-normal :background unspecified ))))
`(org-imminent-deadline ((t (:foreground ,text-match-2 :background unspecified :bold t ))))
`(org-latex-and-related ((t (:foreground ,text-normal :background unspecified ))))
`(org-level-1 ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t ))))
`(org-link ((t (:foreground ,text-link :background unspecified :bold t :underline t ))))
`(org-list-dt ((t (:foreground ,text-normal :background unspecified ))))
`(org-macro ((t (:foreground ,text-normal :background unspecified ))))
`(org-meta-line ((t (:foreground ,text-normal :background unspecified ))))
`(org-property-value ((t (:foreground ,text-normal :background unspecified ))))
`(org-priority ((t (:foreground ,text-hl :background ,background-hl ))))
`(org-quote ((t (:foreground ,text-normal :background unspecified :italic t ))))
`(org-scheduled ((t (:foreground ,text-normal :background unspecified ))))
`(org-sexp-date ((t (:foreground ,text-normal :background unspecified ))))
`(org-special-keyword ((t (:foreground ,text-low :bold t ))))
`(org-table ((t (:foreground ,text-low :background unspecified ))))
`(org-tag ((t (:foreground ,text-directory :background ,background-directory :bold t ))))
`(org-tag-group ((t (:foreground ,text-normal :background unspecified ))))
`(org-target ((t (:foreground ,text-normal :background unspecified :underline t ))))
`(org-time-grid ((t (:foreground ,text-normal :background unspecified ))))
`(org-todo ((t (:foreground ,text-match-2 :background ,background-match-2 :bold t ))))
`(org-upcoming-deadline ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t ))))
`(org-upcoming-distant-deadline ((t (:foreground ,text-lower :background unspecified ))))
`(popup-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-isearch-match ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-mouse-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-selection-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-menu-summary-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-scroll-bar-background-face ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(popup-scroll-bar-foreground-face ((t (:foreground ,text-normal :background ,background-mode-line :bold nil :italic nil ))))
`(popup-summary-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(popup-tip-face ((t (:foreground ,text-normal :background ,background-fringe :bold nil :italic nil ))))
`(region ((t (:foreground ,text-region :background ,background-region ))))
`(secondary-selection ((t (:foreground ,text-normal :background unspecified ))))
`(shadow ((t (:foreground ,text-low :background unspecified ))))
`(show-paren-match ((t (:foreground ,text-match-3 :background ,background-match-3 :bold t ))))
`(shr-link ((t (:foreground ,text-link :background ,background :underline t ))))
`(speed-type-correct ((t (:foreground ,text-lower ))))
`(speed-type-default ((t (:foreground ,text-normal ))))
`(speed-type-mistake ((t (:foreground ,background-diff-current-A ))))
`(swiper-background-match-1-face-1 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-2 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-3 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-background-match-1-face-4 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-line-face ((t (:foreground ,text-match-2 :background ,background-match-2 :bold t ))))
`(swiper-match-face-1 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-match-face-2 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-match-face-3 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(swiper-match-face-4 ((t (:foreground ,text-match-1 :background ,background-match-1 :bold t ))))
`(tab-bar ((t (:foreground ,text-normal :background ,background-mode-line ))))
`(tab-bar-tab ((t (:foreground ,text-low :background ,background-mode-line :bold t :box (:line-width 8 :color ,background-mode-line) ))))
`(tab-bar-tab-group-current ((t (:foreground ,text-normal :background unspecified ))))
`(tab-bar-tab-group-inactive ((t (:foreground ,text-normal :background unspecified ))))
`(tab-bar-tab-inactive ((t (:foreground ,text-normal :background ,background-mode-line :box (:line-width 8 :color ,background-mode-line) ))))
`(tab-bar-tab-ungrouped ((t (:foreground ,text-normal :background unspecified ))))
`(tab-line ((t (:foreground ,text-normal :background unspecified ))))
`(transient-key-exit ((t (:foreground ,text-normal :bold t ))))
`(transient-key-return ((t (:foreground ,text-normal :bold t ))))
`(transient-key-stay ((t (:foreground ,text-normal :bold t ))))
`(transient-red ((t (:foreground ,text-normal :background unspecified ))))
`(treemacs-directory-collapsed-face ((t (:foreground ,text-low :background unspecified ))))
`(treemacs-directory-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-file-face ((t (:foreground ,text-normal :background unspecified ))))
`(treemacs-fringe-indicator-face ((t (:foreground ,background-mode-line :background unspecified :bold t ))))
`(treemacs-git-added-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-ignored-face ((t (:foreground ,text-low :background unspecified :bold t ))))
`(treemacs-git-modified-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-renamed-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(treemacs-git-untracked-face ((t (:foreground ,text-low :background unspecified :bold t ))))
`(treemacs-root-face ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(vertical-border ((t (:foreground ,background ))))
`(warning ((t (:foreground ,text-mode-line :background unspecified :bold t :underline t ))))
`(whitespace-indentation ((t (:foreground ,text-whitespace :background unspecified ))))
`(whitespace-line ((t (:background unspecified ))))
`(whitespace-newline ((t (:foreground ,text-whitespace :background unspecified ))))
`(whitespace-space ((t (:foreground ,text-whitespace :background unspecified ))))
`(whitespace-tab ((t (:foreground ,text-whitespace :background unspecified ))))
`(xref-match ((t (:foreground ,text-normal :background unspecified :bold t ))))
`(ztreep-diff-model-add-face ((t (:foreground ,text-normal :background unspecified ))))
`(ztreep-diff-model-normal-face ((t (:foreground ,text-normal :background unspecified ))))
)

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
           (file-name-as-directory (file-name-directory load-file-name))))

(provide-theme 'chiaroscuro)

;;; chiaroscuro-theme.el ends here
