;;; console dark --- theme
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme/common/variables.el")

(setq background "#000000")
(setq background-diff-added "#698b69")
(setq background-diff-added-highlight "#008b45")
;;(setq background-diff-current-A "#ffaeb9")
;;(setq background-diff-current-Ancestor "#dbdbdb")
;;(setq background-diff-current-B "#c1ffc1")
;;(setq background-diff-current-C "#ffec8b")
;;(setq background-diff-even-A "#dbdbdb")
;;(setq background-diff-even-Ancestor "#dbdbdb")
;;(setq background-diff-even-B "#dbdbdb")
;;(setq background-diff-even-C "#dbdbdb")
;;(setq background-diff-fine-A "#ff82ab")
;;(setq background-diff-fine-Ancestor "#dbdbdb")
;;(setq background-diff-fine-B "#c1ffc1")
;;(setq background-diff-fine-C "#fff68f")
;;(setq background-diff-odd-A "#dbdbdb")
;;(setq background-diff-odd-Ancestor "#dbdbdb")
;;(setq background-diff-odd-B "#dbdbdb")
;;(setq background-diff-odd-C "#dbdbdb")
(setq background-diff-removed "#8b3a3a")
(setq background-diff-removed-highlight "#cd3333")
(setq background-fringe "#1a1a1a")
(setq background-magit "#000000")
(setq background-magit-dark "#000000")
(setq background-mode-line "#0d0d0d")
(setq text-comment "#43cd80")
(setq text-constant "#2e8b57")
(setq text-function "#b9d3ee")
(setq text-highlight-1 "#7fff00")
(setq text-highlight-2 "#d02090")
(setq text-highlight-3 "#ffa500")
(setq text-info "#ffe7ba")
(setq text-keyword "#fa8072")
(setq text-line-number "#cdba96")
(setq text-link "#ba55d3")
(setq text-low "#eed8ae")
(setq text-lower "#cdba96")
(setq text-normal "#ffe7ba")
(setq text-preprocessor "#2e8b57")
(setq text-type "#6c7b8b")
(setq text-variable "#9fb6cd")
(setq text-whitespace "#8b7e66")

;;; console-dark.el ends here
