;;; light --- common colors  -*- lexical-binding: t; -*-
;;; Commentary:
;;; Code:

(load-file "~/.emacs.d/theme/common/variables.el")

(setq background-cursor "#000000")
(setq background-directory "#bbe8ff")
(setq background-fringe "#eeeeee")
(setq background-hl "#fff5a9")
(setq background-hl-low "#f6f3d8")
(setq background-low "#ededed")
(setq background-match-1 "#ffffbb")
(setq background-match-2 "#bbffbb")
(setq background-match-3 "#ffbbbb")
(setq background-match-2-a "#ffbbbb")
(setq background-match-2-b "#ffffbb")
(setq background-match-2-c "#bbe8ff")
(setq background-match-2-d "#bbbbff")
(setq background-mode-line "#cccccc")
(setq background-mode-line-inactive "#eeeeee")
(setq background-region "#bbffbb")
(setq background-tooltip "#eeeeee")
(setq text-delete "#ff0000")
(setq text-directory "#000000")
(setq text-highlight "#7f0055")
(setq text-hl "#000000")
(setq text-hl-low "#000000")
(setq text-hl-lower "#000000")
(setq text-info "#ff0000")
(setq text-match-1 "#000000")
(setq text-match-2 "#000000")
(setq text-match-3 "#000000")
(setq text-match-2-a "#000000")
(setq text-match-2-b "#000000")
(setq text-match-2-c "#000000")
(setq text-match-2-d "#000000")
(setq text-match-2-low "#999999")
(setq text-mode-line "#000000")
(setq text-mode-line-inactive "#999999")
(setq text-region "#000000")
(setq text-whitespace "#cccccc")

;;; light.el ends here
